### ISSUE TITLE
missing packet details

### ISSUE THREAD

**Issue by cleesmith** [jasonish/go-unified2#2]
The equivalent of ```decode_ethernet``` from ```py-idstools/idstools/packet.py``` is missing, as well as:  
```
decode_icmp, decode_icmp6, decode_udp, decode_tcp, decode_ip, and decode_ip6
```
Did I miss something, or is this code I can add?  Any suggestions?

Users liked having these fields, particularly the MAC addresses for some reason:

```
"tcp_flags": 24,
"ether_type": 2048,
"ether_dst": "00:0c:29:b9:39:c3",
"ip_flags": 2,
"ip_version": 4,
"tcp_offset": 5,
"tcp_window": 64860,
"ip_ihl": 5,
"ip_id": 58,
"ether_src": "00:0c:29:92:e9:86",
"tcp_urgptr": 0,
"ip_chksum": 30175,
"ip_protocol": 6,
"ip_length": 180,
"tcp_dport": 80,
"tcp_ack": 2398391695,
"ip_ttl": 128,
"tcp_chksum": 16997,
"ip_offset": 0,
"ip_dscp": 0,
"tcp_seq": 4251506915,
"tcp_sport": 1032
```
Thanks.

**Comment by jasonish** [comment]
With Golang, I think its out of scope to add these decoders to to the unified2 package, but instead create a new package for them.  I'd first check out other packet processing packages first, perhaps https://github.com/google/gopacket - I have not used it myself, but it looks comprehensive.

**Comment by cleesmith** [comment]
That makes sense, just not as simple as python. Thanks for the info.
